import{s as m,r as g,h as u,i as v,a as I,b as M}from"./assets/members-modal-D1kCSRWA.js";import"./assets/hero-kDa5FADt.js";const d=document.querySelector(".trend-cards");async function p(){try{let n=function(t){for(let o=t.length-1;o>0;o--){const s=Math.floor(Math.random()*(o+1));[t[o],t[s]]=[t[s],t[o]]}return t};m();const e=await(await fetch("https://api.themoviedb.org/3/trending/all/day?language=en-US",{method:"GET",headers:{accept:"application/json",Authorization:"Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZTk4ZmY3ODg1ZTM2MWU4Y2UxZDVlYjZkMWQ3ZGU4NiIsIm5iZiI6MTc0MzY4NTIxNS4xNDIwMDAyLCJzdWIiOiI2N2VlODY1ZjAzNTQwY2Y4ZTU2MmI5NWEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.2dJFIqnvzkqw_5VH2b_FLFt5Hwkp3DrqAqyG_61G1pA"}})).json(),y=window.innerWidth<=576?1:3,h=n(e.results).slice(0,y);d.innerHTML="",h.forEach(t=>{const o=document.createElement("li");o.className="cards",o.style.backgroundImage=`url(https://image.tmdb.org/t/p/original${t.poster_path})`;const s=['<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>'];for(let c=0;c<=t.vote_average/2;c++)s[c]='<span class="star star"></span>';o.innerHTML=`
        <div class="about">
          <h3 class="filmm-name">${t.title||t.name}</h3>
          <p class="filmm-content">${t.release_date}</p>
        </div>
        <div class="movies__list-item-rating">
          ${s.join("")}
        </div>
      `,o.addEventListener("click",()=>{g(t)}),d.appendChild(o)})}catch(i){console.error("Veri çekme hatası:",i)}finally{u()}}p();let l=window.innerWidth;window.addEventListener("resize",()=>{(l<=576&&window.innerWidth>576||l>576&&window.innerWidth<=576)&&(l=window.innerWidth,p())});const w=async()=>new Promise((i,a)=>{fetch("https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1",{method:"GET",headers:{accept:"application/json",Authorization:"Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMTU5ZDczMTAzOWRjYWNhYzc1ZjBkNmEyZDUzNzFjYSIsIm5iZiI6MTc0MzIwMzMwOC4zMTQsInN1YiI6IjY3ZTcyYmVjMGU4ZWU2NzgxNTY3YTQ4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.H1VcIsy5PEjzy4uHm47ss9XozIyh5LIka9hEmPAOO3k"}}).then(n=>n.json()).then(n=>{i(n)}).catch(n=>console.error(n))});w().then(i=>{const a=Math.floor(Math.random()*i.results.length),e=i.results[a];document.querySelector("#img-div-upcoming").style.backgroundImage=`url(https://image.tmdb.org/t/p/original${e.poster_path})`,document.querySelector("#upcoming-title").textContent=e.original_title,document.querySelector("#upcoming-date").textContent=e.release_date,document.querySelector("#upcoming-vote").textContent=e.vote_average.toFixed(1),document.querySelector("#upcoming-votes").textContent=e.vote_count,document.querySelector("#upcoming-popularity").textContent=e.popularity;const n={28:"Action",12:"Adventure",16:"Animation",35:"Comedy",80:"Crime",99:"Documentary",18:"Drama",10751:"Family",14:"Fantasy",36:"History",27:"Horror",10402:"Music",9648:"Mystery",10749:"Romance",878:"Science Fiction",10770:"TV Movie",53:"Thriller",10752:"War",37:"Western"};document.querySelector("#upcoming-genres").textContent=e.genre_ids.map(r=>n[r]).join(", "),document.querySelector("#upcoming-overview").textContent=e.overview,v(e.id)?(document.querySelector("#upcoming-add-library").style.display="none",document.querySelector("#upcoming-remove-library").style.display="block"):(document.querySelector("#upcoming-add-library").style.display="block",document.querySelector("#upcoming-remove-library").style.display="none"),document.querySelector("#upcoming-add-library").addEventListener("click",r=>{r.target.style.display="none",I(e),document.querySelector("#upcoming-remove-library").style.display="block"}),document.querySelector("#upcoming-remove-library").addEventListener("click",r=>{document.querySelector("#upcoming-remove-library").style.display="none",M(e),document.querySelector("#upcoming-add-library").style.display="block"})});document.addEventListener("DOMContentLoaded",()=>{m(),window.addEventListener("load",()=>{setTimeout(()=>{u()},500)})});
//# sourceMappingURL=index.js.map
