import{s as p,r as v,h as g}from"./assets/members-modal-VuQz3r8y.js";document.addEventListener("DOMContentLoaded",function(){p();const n=JSON.parse(localStorage.getItem("myLibrary"))||[],l=document.getElementById("filters"),s=document.querySelector(".library-content"),t=document.querySelector(".load-more-btn"),c=document.querySelector("#genre"),e=9;let i=1;const o=document.getElementById("empty-library"),a=document.getElementById("go-to-catalog-btn");if(n.length===0){o.style.display="flex",l.style.display="none",s.style.display="none",t.style.display="none",a.style.display="block",a.addEventListener("click",function(){window.location.href="index.html"});return}else o.style.display="none",a.style.display="none",l.style.display="flex",s.style.display="flex",t.style.display="flex";d(n.slice(0,e)),n.length>e?t.style.display="block":t.style.display="none",c.addEventListener("change",r=>{const y=r.target.value,m=y==="all"?n.slice(0,i*e):n.filter(u=>u.genre_ids.includes(parseInt(y)));m.length===0?(s.innerHTML="",t.style.display="none"):(t.style.display="block",d(m))}),t.addEventListener("click",function(){i++;const r=n.slice(0,i*e);d(r),r.length>=n.length&&(t.style.display="none")})});function d(n,l=!1){const s=document.querySelector(".library-content");l||(s.innerHTML=""),s.innerHTML="",n.forEach((t,c)=>{const e=document.createElement("li");e.className="movies__list-item",e.style.background="linear-gradient(to top, rgba(0, 0, 0, 1), rgba(0, 0, 0, 0))",e.style.backgroundImage=`url(https://image.tmdb.org/t/p/original/${t.poster_path})`,e.style.backgroundSize="cover",e.style.backgroundRepeat="no-repeat",e.style.width="395px",e.style.height="574px",e.style.overflow="hidden",e.style.borderRadius="5px",e.style.color="white",e.style.position="relative",e.style.cursor="pointer",e.addEventListener("click",i=>{v(t)}),e.innerHTML=`
                        <div class="movies__list-item-info">
                            <div class="movies__list-item-info-container">
                            <h3 class="movies__list-item-title">${t.title||t.name}</h3>
                            <p class="movies__list-item-description">${t.release_date}</p>
                            </div>
                            <div class="movies__list-item-rating">
                             ${Array.from({length:5},(i,o)=>o<Math.round(t.vote_average)?'<img src="./images/star.png" alt="star">':'<img src="./images/star-outline.png" alt="empty star">').join("")}
                            </div>
                        </div>
                    `,s.appendChild(e)})}window.addEventListener("load",()=>{setTimeout(()=>{g()},500)});document.addEventListener("DOMContentLoaded",()=>{p(),window.addEventListener("load",()=>{setTimeout(()=>{g()},500)})});
//# sourceMappingURL=myLibrary.js.map
