import{s as m,h as p}from"./assets/members-modal-ePwIciLd.js";document.addEventListener("DOMContentLoaded",function(){m();const t=JSON.parse(localStorage.getItem("myLibrary"))||[],o=document.getElementById("filters"),i=document.getElementById("movie-grid"),l=document.querySelector(".load-more-btn"),e=9;let a=1;const r=document.getElementById("empty-library"),c=document.getElementById("go-to-catalog-btn");if(t.length===0){r.style.display="flex",o.style.display="none",i.style.display="none",l.style.display="none",c.style.display="block",c.addEventListener("click",function(){window.location.href="index.html"});return}else r.style.display="none",c.style.display="none",o.style.display="block",i.style.display="block",l.style.display="block";d(t.slice(0,e)),t.length>e?l.style.display="block":l.style.display="none",[...new Set(t.flatMap(n=>n.genres))].forEach(n=>{const s=document.createElement("option");s.value=n,s.textContent=n,o.appendChild(s)}),o.addEventListener("change",function(){const n=this.value,s=t.filter(y=>y.genres.includes(n));d(s)}),l.addEventListener("click",function(){a++;const n=(a-1)*pageSize,s=n+pageSize,y=t.slice(n,s);d(y),s>=t.length&&(l.style.display="none")}),i.addEventListener("click",function(n){if(n.target.classList.contains("delete-btn")){const s=n.target.dataset.index;t.splice(s,1),localStorage.setItem("myLibrary",JSON.stringify(t)),d(t.slice(0,pageSize))}})});function d(t){const o=document.getElementById("movie-grid");o.innerHTML="",t.forEach((i,l)=>{console.log(i);const e=document.createElement("li");e.className="movies__list-item",e.style.background="linear-gradient(to top, rgba(0, 0, 0, 1), rgba(0, 0, 0, 0))",e.style.backgroundImage=`url(https://image.tmdb.org/t/p/original${i.poster_path})`,e.style.backgroundSize="cover",e.style.backgroundRepeat="no-repeat",e.style.width="395px",e.style.height="574px",e.style.overflow="hidden",e.style.borderRadius="5px",e.style.color="white",e.style.position="relative",e.style.cursor="pointer",e.addEventListener("click",a=>{document.querySelector(".infoPopup").style.display="flex"}),e.innerHTML=`
                        <div class="movies__list-item-info">
                            <div class="movies__list-item-info-container">
                            <h3 class="movies__list-item-title">${i.title||i.name}</h3>
                            <p class="movies__list-item-description">${i.release_date}</p>
                            </div>
                            <div class="movies__list-item-rating">
                             ${Array.from({length:5},(a,r)=>r<Math.round(i.vote_average)?'<img src="./images/star.png" alt="star">':'<img src="./images/star-outline.png" alt="empty star">').join("")}
                            </div>
                        </div>
                    `,o.appendChild(e)})}window.addEventListener("load",()=>{setTimeout(()=>{p()},500)});document.addEventListener("DOMContentLoaded",()=>{m(),window.addEventListener("load",()=>{setTimeout(()=>{p()},500)})});
//# sourceMappingURL=myLibrary.js.map
