import{s as m,r as v,h as u}from"./assets/members-modal-ifmCCDvs.js";document.addEventListener("DOMContentLoaded",function(){m();const s=JSON.parse(localStorage.getItem("myLibrary"))||[],a=document.getElementById("filters"),n=document.querySelector(".library-content"),t=document.querySelector(".load-more-btn"),c=document.querySelector("#genre"),e=9;let i=1;const l=document.getElementById("empty-library"),r=document.getElementById("go-to-catalog-btn");if(s.length===0){l.style.display="flex",a.style.display="none",n.style.display="none",t.style.display="none",r.style.display="block",r.addEventListener("click",function(){window.location.href="index.html"});return}else l.style.display="none",r.style.display="none",a.style.display="flex",n.style.display="flex",t.style.display="flex";d(s.slice(0,e)),s.length>e?t.style.display="block":t.style.display="none",c.addEventListener("change",o=>{const y=o.target.value,p=y==="all"?s.slice(0,i*e):s.filter(g=>g.genre_ids.includes(parseInt(y)));p.length===0?(n.innerHTML="",t.style.display="none"):(t.style.display="block",d(p))}),t.addEventListener("click",function(){i++;const o=s.slice(0,i*e);d(o),o.length>=s.length&&(t.style.display="none")})});function d(s,a=!1){const n=document.querySelector(".library-content");a||(n.innerHTML=""),n.innerHTML="",s.forEach((t,c)=>{const e=document.createElement("li");e.className="movies__list-item",e.style.background="linear-gradient(to top, rgba(0, 0, 0, 1), rgba(0, 0, 0, 0))",e.style.backgroundImage=`url(https://image.tmdb.org/t/p/original/${t.poster_path})`,e.style.backgroundSize="cover",e.style.backgroundRepeat="no-repeat",e.style.width="395px",e.style.height="574px",e.style.overflow="hidden",e.style.borderRadius="5px",e.style.color="white",e.style.position="relative",e.style.cursor="pointer",e.addEventListener("click",l=>{v(t)});const i=['<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>','<span class="star star-outline"></span>'];for(let l=0;l<=Math.round(t.vote_average/2);l++)i[l]='<span class="star star"></span>';e.innerHTML=`
                        <div class="movies__list-item-info">
                            <div class="movies__list-item-info-container">
                            <h3 class="movies__list-item-title">${t.title||t.name}</h3>
                            <p class="movies__list-item-description">${t.release_date}</p>
                            </div>
                            <div class="movies__list-item-rating">
                            ${i.join("")}
                            </div>
                        </div>
                    `,n.appendChild(e)})}window.addEventListener("load",()=>{setTimeout(()=>{u()},500)});document.addEventListener("DOMContentLoaded",()=>{m(),window.addEventListener("load",()=>{setTimeout(()=>{u()},500)})});
//# sourceMappingURL=myLibrary.js.map
